function MainPage() {
  return (
    <>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
      <div>MainPage</div>
    </>
  );
}

export default MainPage;
